apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:18
        command: ["sh", "-c"]
        args:
          - |
            npm install -g json-server &&
            echo '{"posts":[{"id":1,"title":"Hello DevOps"}]}' > db.json &&
            json-server --watch db.json --host 0.0.0.0
        ports:
          - containerPort: 3000
